services:
  db:
    image: postgres:18-alpine
    container_name: auth-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: SimpleAuthDb
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  api:
    build: .
    container_name: auth-api
    depends_on:
      - db
    ports:
      - "5257:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Database=SimpleAuthDb;Username=postgres;Password=${POSTGRES_PASSWORD};
      - Jwt__Key=${JWT_KEY}
volumes:
  db-data: